modules:
  reservations:
    name: Reservation
    model: KepplerShopReservation
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  products:
    name: Product
    model: KepplerShopProduct
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  shippings:
    name: Shipping
    model: KepplerShopShipping
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]
